panel.url=http://127.0.0.1:8088
panel.api-token=CHANGE_ME

ticket.default-category=SUPPORT
ticket.default-priority=NORMAL
ticket.list-limit=8

litebans.enabled=true
litebans.join-check=true
litebans.server-scope=*
litebans.ban-command=ban {player} {duration} {reason}
litebans.unban-command=unban {player} {reason}

permissions.ticket-create=tccb.ticket.create
permissions.ticket-list-own=tccb.ticket.own
permissions.ticket-team=tccb.ticket.team
permissions.ticket-manage=tccb.ticket.manage
permissions.ban-manage=tccb.ban.manage
permissions.reload=tccb.reload
